[build]
  base = "client/"
  publish = "dist/"
  command = "npm run generate"

[[redirects]]
  from = "/api/*"
  to = "https://website-analyzer-app.herokuapp.com/api"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
