[build]
  base = "client/"
  publish = "dist/"
  command = "npm run generate"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://website-analyzer-app.herokuapp.com/api"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
