[build]
  base = "client/"
  publish = "dist/"
  command = "npm run generate"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

  for="/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
